# @name login
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username":"admin", 
    "password":"123456" 
}

###
DELETE http://localhost:3001/api/blogs/6161152303704da5eff08dd1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}